extends: airbnb
parser: babel-eslint
plugins:
  - babel
rules:
  arrow-parens: [off]
  babel/arrow-parens: [warn, as-needed]
  import/no-mutable-exports: [off]
  import/prefer-default-export: [off]
  no-case-declarations: [off]
  no-console: [off]
  no-param-reassign: [warn, { props: false }]
  no-restricted-syntax: [off]
  no-throw-literal: [off]
  no-underscore-dangle: [off]
  no-use-before-define: [warn, { functions: false }]
  prefer-const: [warn]
  react/no-multi-comp: [off]
  react/no-unused-prop-types: [warn]
  react/forbid-prop-types: [off]
