# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 15:11
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=32)),
                ('ftp_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=32)),
                ('addons', models.ManyToManyField(related_name='groups', to='addons.Addon')),
            ],
        ),
    ]
