# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 11:10
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_auto_20160906_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='addongroup',
            name='no_update_version',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
