# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:38
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_addongroup_no_update_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addongroup',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='addongroup',
            name='no_update_version',
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='browser_version',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
