# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 04:58
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0004_auto_20160927_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='addongroup',
            name='built_in_addons',
            field=models.ManyToManyField(related_name='built_in_groups', to='addons.Addon'),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='qa_addons',
            field=models.ManyToManyField(related_name='qa_groups', to='addons.Addon'),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='shipped_addons',
            field=models.ManyToManyField(related_name='shipped_groups', to='addons.Addon'),
        ),
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together=set([('name', 'version')]),
        ),
    ]
