# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0008_auto_20161026_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addongroup',
            old_name='browser_version_tmp',
            new_name='browser_version',
        ),
        migrations.AlterModelOptions(
            name='addongroup',
            options={'ordering': ('-browser_version',)},
        ),
    ]
