# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


def remap_versions(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')

    for addon in Addon.objects.all():
        addon.version_tmp = addon.version
        addon.save()


def undo_remap_versions(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')

    for addon in Addon.objects.all():
        addon.version = str(addon.version_tmp)
        addon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0010_auto_20161026_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='version',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(remap_versions, undo_remap_versions),
    ]
