# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:00
from __future__ import unicode_literals

from django.db import migrations
import morgoth.addons.models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0011_auto_20161026_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='version',
        ),
        migrations.AlterField(
            model_name='addon',
            name='version_tmp',
            field=morgoth.addons.models.VersionNumberField(unique=True),
        ),
    ]
