# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0012_auto_20161026_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='version_tmp',
            new_name='version',
        ),
    ]
