# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 20:01
from __future__ import unicode_literals

from django.db import migrations
import morgoth.addons.models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0013_auto_20161026_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='version',
            field=morgoth.addons.models.VersionNumberField(),
        ),
    ]
